stages:
- build
- release

build:
  stage: build
  image: python:3.7
  script:
  - pip install poetry
  - poetry install
  - poetry build
  artifacts:
    expire_in: 6 months
    paths:
    - dist/

release:tag:
  stage: release
  image: python:3.7
  only:
  - tags
  script:
  - pip3 install gitlab-release
  - poetry config repositories.microquake https://pkg.microquake.org
  - poetry config http-basic.microquake $PYPI_USER $PYPI_PASS
  - poetry publish -r microquake
  - gitlab-release --link-artifact ./dist/*whl
  artifacts:
    paths:
    - dist/*whl
